### ISSUE TITLE
How well this template functions with wireUI?(Question)

### ISSUE THREAD

**Issue by BenceBakos** [TailAdmin/tailadmin-free-tailwind-dashboard-template#2]
Any experience with large-scale projects?

**Comment by Musharofchy** [comment]
Thanks for your query on this. Its plain Tailwind CSS template and we used alpine.js for interactions. You can definitely use on your large-scale projects but we don't have any metrics to share and didn't try with wireUI. We're open for feedback, join and chat us here: https://pimjo.com/discord
