### ISSUE TITLE
Issue applying to Laravel

### ISSUE THREAD

**Issue by Musharofchy** [TailAdmin/tailadmin-free-tailwind-dashboard-template#6]
### Discussed in https://github.com/orgs/TailAdmin/discussions/5

<div type='discussions-op-text'>

<sup>Originally posted by **Scottzozer** December 26, 2023</sup>
Hi All, 

Trying to use this template on a Laravel 10 project but keep running into issues when trying to merge it into my project. Right now I am getting an error on almost all of the custom CSS @apply classes saying they do not exist. Probably a noob mistake somewhere but I have added all the necessary libraries from the package.json, npm installed to generate all the node modules, added all the files, images, css, js to my project. Updated paths so they are in Laravel syntax but still getting these errors:

`style.css:40:3: The 'border-primary' class does not exist. If 'border-primary' is a custom class, make sure it is defined within a '@layer' directive.`

Anyone have any ideas on how to solve? </div>

**Comment by Coderamrin** [comment]
Hello,
This might be a configuration issue. 
Please follow the Tailwind CSS docs to complete the configuration. 
https://tailwindcss.com/docs/guides/laravel#vite

And follow these if it still available.
https://stackoverflow.com/questions/68422354/tailwind-is-not-working-on-a-new-laravel-project
https://github.com/tailwindlabs/tailwindcss/issues/53

**Comment by sabri-ayadi** [comment]
same issue with me when i run my app i get this error 
[plugin:vite:import-analysis] Failed to resolve import "jsvectormap/dist/css/jsvectormap.css" from "resources/js/index.js". Does the file exist?
but everything is in place, does this repo miss some extra files?
